_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en-gb
uuid: de8eef85-1c01-44a7-b0e1-08b228afcf5f
name: Glint
mail: allan.thecodemaster@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
